
/*-
 * ============LICENSE_START==========================================
 * OPENECOMP - DCAE
 * ===================================================================
 * Copyright (c) 2017 AT&T Intellectual Property. All rights reserved.
 * ===================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0 
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ============LICENSE_END============================================
 */
	
// Autogenerated
// Do not edit. No need to extend this class.
package org.openecomp.ncomp.servers.docker;

import org.openecomp.ncomp.sirius.manager.AbstractClient;
import org.openecomp.ncomp.sirius.manager.HighAvailabilityClient;
import org.openecomp.ncomp.sirius.manager.GenericHttpClient;

import org.apache.log4j.Logger;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.openecomp.ncomp.docker.impl.DockerHostImpl;
import org.openecomp.ncomp.docker.DockerPackage;


import org.openecomp.ncomp.servers.docker.DockerDockerAdaptor; 



 
@SuppressWarnings("unchecked")
public class DockerDockerHostClient extends DockerHostImpl {
	public static final Logger logger = Logger.getLogger(DockerDockerHostClient.class);
	public AbstractClient client;

	public DockerDockerHostClient(String file, String name) {
		DockerDockerAdaptor.ecoreSetup(); 
		client = new GenericHttpClient(file,name);
		client.add("/host", this);
	}

	public DockerDockerHostClient(String file, String name1, String name2) {
		HighAvailabilityClient client1 = new HighAvailabilityClient(file,name1,name2);
		client = client1.all; // requests should be forwarded to all.
		client.add("/host", this);
	}
	
	public DockerDockerHostClient(AbstractClient c) {
		client = c;
		client.add("/resources", this);
	}



	
	public void poll(String path) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "poll", null);
	}

	
	public void startContainer(String path, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "startContainer", null, name);
	}

	
	public void stopContainer(String path, java.lang.String name, int seconds) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "stopContainer", null, name,seconds);
	}

	
	public void restartContainer(String path, java.lang.String name, int seconds) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "restartContainer", null, name,seconds);
	}

	
	public void pauseContainer(String path, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "pauseContainer", null, name);
	}

	
	public void unpauseContainer(String path, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "unpauseContainer", null, name);
	}

	
	public void removeContainer(String path, java.lang.String name, boolean remove, boolean force) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "removeContainer", null, name,remove,force);
	}

	
	public void inspectContainer(String path, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "inspectContainer", null, name);
	}

	
	public void killContainer(String path, java.lang.String name, java.lang.String sigint) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "killContainer", null, name,sigint);
	}

	
	public void dockerRun(String path, java.lang.String image) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "dockerRun", null, image);
	}

	
	public void dockerRunWithName(String path, java.lang.String image, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "dockerRunWithName", null, image,name);
	}

	
	public void dockerRunWithOptions(String path, java.lang.String image, org.openecomp.ncomp.docker.ContainerOptions opts) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "dockerRunWithOptions", null, image,opts);
	}

	
	public void containerStats(String path, java.lang.String name, boolean stream) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "containerStats", null, name,stream);
	}

	
	public void containerProcesses(String path, java.lang.String name) {
		EClass c = DockerPackage.eINSTANCE.getDockerHost(); //foo
		client.operationPath(path, c, "containerProcesses", null, name);
	}

}
